import { defineStackbitConfig } from "@stackbit/types";
import { GitContentSource } from "@stackbit/cms-git";

export default defineStackbitConfig({
  stackbitVersion: "~0.6.0",
  ssgName: "custom",
  nodeVersion: "18",
  devCommand:
    "node_modules/.bin/astro dev --port {PORT} --hostname 127.0.0.1",
  experimental: {
    ssg: {
      name: "Astro",
      logPatterns: {
        up: ["is ready", "astro"],
      },
      directRoutes: {
        "socket.io": "socket.io",
      },
      passthrough: ["/vite-hmr/**"],
    },
  },
  contentSources: [
    new GitContentSource({
      rootPath: __dirname,
      contentDirs: [
        "src/content/updates",
        "src/content/press-releases",
        "src/content/press",
        "src/content/board-members",
        "src/content/documents",
        "src/content/testimonials",
        "src/content/timeline",
        "src/content/resources",
        "src/content/pages",
      ],
      models: [
        // ── Updates (Markdown with frontmatter) ──
        {
          name: "Update",
          type: "page",
          urlPath: "/progress/updates/{slug}",
          filePath: "src/content/updates/{slug}.md",
          fields: [
            { name: "title", type: "string", required: true },
            { name: "pubDate", type: "date", required: true },
            { name: "description", type: "string", required: true },
            { name: "author", type: "string" },
            { name: "authorTitle", type: "string" },
            { name: "featuredImage", type: "image" },
            { name: "featuredImageAlt", type: "string" },
            {
              name: "tags",
              type: "list",
              items: { type: "string" },
            },
            {
              name: "status",
              type: "enum",
              options: [
                "planning",
                "funded",
                "engagement",
                "construction",
                "complete",
              ],
            },
            { name: "draft", type: "boolean", default: false },
            { name: "body", type: "markdown", required: false },
          ],
        },

        // ── Press Releases (Markdown with frontmatter) ──
        {
          name: "PressRelease",
          type: "page",
          urlPath: "/press/{slug}",
          filePath: "src/content/press-releases/{slug}.md",
          fields: [
            { name: "title", type: "string", required: true },
            { name: "pubDate", type: "date", required: true },
            { name: "summary", type: "string", required: true },
            { name: "contactName", type: "string" },
            { name: "contactEmail", type: "string" },
            { name: "contactPhone", type: "string" },
            { name: "draft", type: "boolean", default: false },
            { name: "body", type: "markdown", required: false },
          ],
        },

        // ── Press Coverage (JSON data) ──
        {
          name: "Press",
          type: "data",
          filePath: "src/content/press/{slug}.json",
          fields: [
            { name: "outlet", type: "string", required: true },
            { name: "title", type: "string", required: true },
            { name: "date", type: "date", required: true },
            { name: "link", type: "url", required: true },
            {
              name: "mediaType",
              type: "enum",
              options: ["article", "radio", "tv", "podcast"],
              default: "article",
            },
          ],
        },

        // ── Board Members (JSON data) ──
        {
          name: "BoardMember",
          type: "data",
          filePath: "src/content/board-members/{slug}.json",
          fields: [
            { name: "name", type: "string", required: true },
            { name: "title", type: "string", required: true },
            {
              name: "role",
              type: "enum",
              options: [
                "chair",
                "vice-president",
                "treasurer",
                "secretary",
                "board-member",
                "staff",
                "emeritus",
              ],
              required: true,
            },
            { name: "bio", type: "text", required: true },
            { name: "photo", type: "image" },
            { name: "order", type: "number", required: true },
          ],
        },

        // ── Documents (JSON data) ──
        {
          name: "Document",
          type: "data",
          filePath: "src/content/documents/{slug}.json",
          fields: [
            { name: "title", type: "string", required: true },
            { name: "agency", type: "string", required: true },
            { name: "year", type: "number", required: true },
            {
              name: "documentType",
              type: "enum",
              options: ["plan", "study", "policy", "report"],
              required: true,
            },
            { name: "file", type: "string" },
            { name: "link", type: "url" },
            {
              name: "level",
              type: "enum",
              options: [
                "federal",
                "state",
                "regional",
                "county",
                "city",
              ],
            },
            { name: "description", type: "text" },
          ],
        },

        // ── Testimonials (JSON data) ──
        {
          name: "Testimonial",
          type: "data",
          filePath: "src/content/testimonials/{slug}.json",
          fields: [
            { name: "quote", type: "text", required: true },
            { name: "author", type: "string", required: true },
            { name: "title", type: "string", required: true },
            { name: "organization", type: "string", required: true },
            { name: "date", type: "date" },
            { name: "pdfFile", type: "string", required: true },
            { name: "order", type: "number" },
          ],
        },

        // ── Timeline (JSON data) ──
        {
          name: "TimelineEntry",
          type: "data",
          filePath: "src/content/timeline/{slug}.json",
          fields: [
            { name: "date", type: "string", required: true },
            { name: "title", type: "string", required: true },
            { name: "description", type: "text", required: true },
            { name: "order", type: "number", required: true },
            {
              name: "images",
              type: "list",
              items: {
                type: "object",
                fields: [
                  { name: "src", type: "image", required: true },
                  { name: "alt", type: "string", required: true },
                  { name: "caption", type: "string" },
                  { name: "credit", type: "string" },
                ],
              },
            },
          ],
        },

        // ── Resources (JSON data) ──
        {
          name: "Resource",
          type: "data",
          filePath: "src/content/resources/{slug}.json",
          fields: [
            { name: "name", type: "string", required: true },
            { name: "description", type: "text", required: true },
            {
              name: "qualities",
              type: "list",
              items: {
                type: "enum",
                options: [
                  "Cultural",
                  "Historical",
                  "Archaeological",
                  "Recreational",
                  "Natural",
                  "Scenic",
                ],
              },
              required: true,
            },
            {
              name: "coordinates",
              type: "object",
              fields: [
                { name: "lat", type: "number", required: true },
                { name: "lng", type: "number", required: true },
              ],
            },
          ],
        },

        // ── Page Content (JSON data for static pages) ──

        // Homepage
        {
          name: "HomePage",
          type: "page",
          urlPath: "/",
          filePath: "src/content/pages/home.json",
          fields: [
            { name: "heroTitle", type: "string", required: true },
            { name: "heroSubtitle", type: "string", required: true },
            { name: "heroImage", type: "image" },
            { name: "heroImageAlt", type: "string" },
            { name: "aboutHeading", type: "string", required: true },
            { name: "aboutBody1", type: "text", required: true },
            { name: "aboutBody2", type: "text" },
            { name: "aboutBody3", type: "text" },
            { name: "aboutImage", type: "image" },
            { name: "aboutImageAlt", type: "string" },
            { name: "challengeHeading", type: "string", required: true },
            { name: "challengeBody", type: "text", required: true },
            { name: "challengeImage", type: "image" },
            { name: "challengeImageAlt", type: "string" },
            { name: "challengeStat1Value", type: "string" },
            { name: "challengeStat1Description", type: "string" },
            { name: "challengeStat2Value", type: "string" },
            { name: "challengeStat2Description", type: "string" },
            { name: "challengeStat3Value", type: "string" },
            { name: "challengeStat3Description", type: "string" },
            { name: "challengeStat4Value", type: "string" },
            { name: "challengeStat4Description", type: "string" },
            { name: "solutionHeading", type: "string", required: true },
            { name: "solutionBody", type: "text", required: true },
            { name: "solutionMapImage", type: "image" },
            { name: "solutionMapImageAlt", type: "string" },
            { name: "solutionComponent1Title", type: "string" },
            { name: "solutionComponent1Description", type: "text" },
            { name: "solutionComponent2Title", type: "string" },
            { name: "solutionComponent2Description", type: "text" },
            { name: "solutionComponent3Title", type: "string" },
            { name: "solutionComponent3Description", type: "text" },
            { name: "ctaHeading", type: "string", required: true },
            { name: "ctaBody", type: "text", required: true },
          ],
        },

        // About Page
        {
          name: "AboutPage",
          type: "page",
          urlPath: "/about",
          filePath: "src/content/pages/about.json",
          fields: [
            { name: "heroLabel", type: "string" },
            { name: "heroTitle", type: "string", required: true },
            { name: "heroDescription", type: "text" },
            { name: "purposeStatement", type: "text", required: true },
            { name: "purposeBody1", type: "text", required: true },
            { name: "purposeBody2", type: "text" },
            { name: "historyHeading", type: "string", required: true },
            { name: "historyDescription", type: "text" },
            { name: "mergerHeading", type: "string", required: true },
            { name: "mergerBody1", type: "text", required: true },
            { name: "mergerBody2", type: "text" },
            { name: "mergerBody3", type: "text" },
            { name: "mergerHighlightTitle", type: "string" },
            { name: "mergerStat1Value", type: "string" },
            { name: "mergerStat1Label", type: "string" },
            { name: "mergerStat2Value", type: "string" },
            { name: "mergerStat2Label", type: "string" },
            { name: "mergerStat3Value", type: "string" },
            { name: "mergerStat3Label", type: "string" },
            { name: "valuesHeading", type: "string" },
            { name: "valuesDescription", type: "text" },
            { name: "leadershipHeading", type: "string" },
            { name: "leadershipDescription", type: "text" },
            { name: "emeritusHeading", type: "string" },
            { name: "emeritusDescription", type: "text" },
            { name: "documentsHeading", type: "string" },
            { name: "documentsDescription", type: "text" },
            { name: "ctaTitle", type: "string" },
            { name: "ctaDescription", type: "text" },
          ],
        },

        // Progress Page
        {
          name: "ProgressPage",
          type: "page",
          urlPath: "/progress",
          filePath: "src/content/pages/progress.json",
          fields: [
            { name: "heroLabel", type: "string" },
            { name: "heroTitle", type: "string", required: true },
            { name: "heroDescription", type: "text" },
            { name: "grantHeading", type: "string", required: true },
            { name: "grantBody", type: "text", required: true },
            { name: "grantAmount", type: "string" },
            { name: "grantAmountLabel", type: "string" },
            { name: "milestonesHeading", type: "string" },
            { name: "updatesHeading", type: "string" },
            { name: "ctaTitle", type: "string" },
            { name: "ctaDescription", type: "text" },
          ],
        },

        // Support Page
        {
          name: "SupportPage",
          type: "page",
          urlPath: "/support",
          filePath: "src/content/pages/support.json",
          fields: [
            { name: "heroLabel", type: "string" },
            { name: "heroTitle", type: "string", required: true },
            { name: "heroDescription", type: "text" },
            { name: "membershipHeading", type: "string", required: true },
            { name: "membershipDescription", type: "text" },
            { name: "taxNote", type: "string" },
            { name: "otherWaysHeading", type: "string" },
            { name: "otherWaysDescription", type: "text" },
          ],
        },

        // Planning Page
        {
          name: "PlanningPage",
          type: "page",
          urlPath: "/progress/planning",
          filePath: "src/content/pages/planning.json",
          fields: [
            { name: "heroLabel", type: "string" },
            { name: "heroTitle", type: "string", required: true },
            { name: "heroDescription", type: "text" },
            { name: "introBody1", type: "text", required: true },
            { name: "introBody2", type: "text" },
            { name: "plansHeading", type: "string" },
            { name: "ctaTitle", type: "string" },
            { name: "ctaDescription", type: "text" },
          ],
        },

        // Press Page
        {
          name: "PressPage",
          type: "page",
          urlPath: "/press",
          filePath: "src/content/pages/press.json",
          fields: [
            { name: "heroLabel", type: "string" },
            { name: "heroTitle", type: "string", required: true },
            { name: "heroDescription", type: "text" },
            { name: "boilerplate", type: "text", required: true },
            { name: "mediaContactEmail", type: "string" },
            { name: "ctaTitle", type: "string" },
            { name: "ctaDescription", type: "text" },
          ],
        },

        // Community Support Page
        {
          name: "CommunitySupportPage",
          type: "page",
          urlPath: "/about/community-support",
          filePath: "src/content/pages/community-support.json",
          fields: [
            { name: "heroLabel", type: "string" },
            { name: "heroTitle", type: "string", required: true },
            { name: "heroDescription", type: "text" },
            { name: "ctaTitle", type: "string" },
            { name: "ctaDescription", type: "text" },
          ],
        },

        // Corridor Page
        {
          name: "CorridorPage",
          type: "page",
          urlPath: "/about/corridor",
          filePath: "src/content/pages/corridor.json",
          fields: [
            { name: "heroLabel", type: "string" },
            { name: "heroTitle", type: "string", required: true },
            { name: "heroDescription", type: "text" },
            { name: "overviewHeading", type: "string", required: true },
            { name: "overviewBody1", type: "text", required: true },
            { name: "overviewBody2", type: "text" },
            { name: "overviewBody3", type: "text" },
            { name: "sidebarTitle", type: "string" },
            { name: "statTotalLength", type: "string" },
            { name: "statExistingHighway", type: "string" },
            { name: "statNortheastExtension", type: "string" },
            { name: "statSouthwestExtension", type: "string" },
            { name: "statIntrinsicResources", type: "string" },
            { name: "statDesignation", type: "string" },
            { name: "greenwayHeading", type: "string", required: true },
            { name: "greenwayBody1", type: "text", required: true },
            { name: "greenwayBody2", type: "text" },
            { name: "greenwayBody3", type: "text" },
            { name: "resourcesHeading", type: "string" },
            { name: "resourcesDescription", type: "text" },
            { name: "ctaTitle", type: "string" },
            { name: "ctaDescription", type: "text" },
          ],
        },

        // Impact Page
        {
          name: "ImpactPage",
          type: "page",
          urlPath: "/about/impact",
          filePath: "src/content/pages/impact.json",
          fields: [
            { name: "heroLabel", type: "string" },
            { name: "heroTitle", type: "string", required: true },
            { name: "heroDescription", type: "text" },
            { name: "safetyLabel", type: "string" },
            { name: "safetyHeading", type: "string", required: true },
            { name: "safetyBody", type: "text", required: true },
            // Safety Stats (4 items)
            { name: "safetyStat1Value", type: "string" },
            { name: "safetyStat1Description", type: "string" },
            { name: "safetyStat1SourceUrl", type: "url" },
            { name: "safetyStat1SourceLabel", type: "string" },
            { name: "safetyStat2Value", type: "string" },
            { name: "safetyStat2Description", type: "string" },
            { name: "safetyStat2SourceUrl", type: "url" },
            { name: "safetyStat2SourceLabel", type: "string" },
            { name: "safetyStat3Value", type: "string" },
            { name: "safetyStat3Description", type: "string" },
            { name: "safetyStat3SourceUrl", type: "url" },
            { name: "safetyStat3SourceLabel", type: "string" },
            { name: "safetyStat4Value", type: "string" },
            { name: "safetyStat4Description", type: "string" },
            { name: "safetyStat4SourceUrl", type: "url" },
            { name: "safetyStat4SourceLabel", type: "string" },
            { name: "mapCaption", type: "text" },
            { name: "mapSourceText", type: "string" },
            { name: "mapSourceUrl", type: "url" },
            { name: "mapSourceAgency", type: "string" },
            { name: "contextProblemHeading", type: "string" },
            { name: "contextProblemBody1", type: "text" },
            { name: "contextProblemBody2", type: "text" },
            { name: "contextProblemBody3", type: "text" },
            { name: "contextSolutionHeading", type: "string" },
            { name: "contextSolutionBody1", type: "text" },
            { name: "contextSolutionBody2", type: "text" },
            { name: "contextSolutionBody3", type: "text" },
            { name: "economicLabel", type: "string" },
            { name: "economicHeading", type: "string", required: true },
            { name: "economicBody", type: "text", required: true },
            // Research Highlights (3 items)
            { name: "research1Value", type: "string" },
            { name: "research1Description", type: "string" },
            { name: "research1SourceUrl", type: "url" },
            { name: "research1SourceLabel", type: "string" },
            { name: "research2Value", type: "string" },
            { name: "research2Description", type: "string" },
            { name: "research2SourceUrl", type: "url" },
            { name: "research2SourceLabel", type: "string" },
            { name: "research3Value", type: "string" },
            { name: "research3Description", type: "string" },
            { name: "research3SourceUrl", type: "url" },
            { name: "research3SourceLabel", type: "string" },
            // Pillar Cards (4 items, each with 2 stats)
            { name: "pillar1Title", type: "string" },
            { name: "pillar1Description", type: "text" },
            { name: "pillar1Detail", type: "text" },
            { name: "pillar1Stat1Value", type: "string" },
            { name: "pillar1Stat1Label", type: "string" },
            { name: "pillar1Stat1SourceUrl", type: "url" },
            { name: "pillar1Stat1SourceLabel", type: "string" },
            { name: "pillar1Stat2Value", type: "string" },
            { name: "pillar1Stat2Label", type: "string" },
            { name: "pillar1Stat2SourceUrl", type: "url" },
            { name: "pillar1Stat2SourceLabel", type: "string" },
            { name: "pillar2Title", type: "string" },
            { name: "pillar2Description", type: "text" },
            { name: "pillar2Detail", type: "text" },
            { name: "pillar2Stat1Value", type: "string" },
            { name: "pillar2Stat1Label", type: "string" },
            { name: "pillar2Stat1SourceUrl", type: "url" },
            { name: "pillar2Stat1SourceLabel", type: "string" },
            { name: "pillar2Stat2Value", type: "string" },
            { name: "pillar2Stat2Label", type: "string" },
            { name: "pillar2Stat2SourceUrl", type: "url" },
            { name: "pillar2Stat2SourceLabel", type: "string" },
            { name: "pillar3Title", type: "string" },
            { name: "pillar3Description", type: "text" },
            { name: "pillar3Detail", type: "text" },
            { name: "pillar3Stat1Value", type: "string" },
            { name: "pillar3Stat1Label", type: "string" },
            { name: "pillar3Stat1SourceUrl", type: "url" },
            { name: "pillar3Stat1SourceLabel", type: "string" },
            { name: "pillar3Stat2Value", type: "string" },
            { name: "pillar3Stat2Label", type: "string" },
            { name: "pillar3Stat2SourceUrl", type: "url" },
            { name: "pillar3Stat2SourceLabel", type: "string" },
            { name: "pillar4Title", type: "string" },
            { name: "pillar4Description", type: "text" },
            { name: "pillar4Detail", type: "text" },
            { name: "pillar4Stat1Value", type: "string" },
            { name: "pillar4Stat1Label", type: "string" },
            { name: "pillar4Stat1SourceUrl", type: "url" },
            { name: "pillar4Stat1SourceLabel", type: "string" },
            { name: "pillar4Stat2Value", type: "string" },
            { name: "pillar4Stat2Label", type: "string" },
            { name: "pillar4Stat2SourceUrl", type: "url" },
            { name: "pillar4Stat2SourceLabel", type: "string" },
            // Evidence Cards (4 items, each with 3 stats)
            { name: "evidenceHeading", type: "string" },
            { name: "evidenceBody", type: "text" },
            { name: "evidence1Title", type: "string" },
            { name: "evidence1Location", type: "string" },
            { name: "evidence1SourceUrl", type: "url" },
            { name: "evidence1SourceLabel", type: "string" },
            { name: "evidence1Stat1Value", type: "string" },
            { name: "evidence1Stat1Description", type: "string" },
            { name: "evidence1Stat2Value", type: "string" },
            { name: "evidence1Stat2Description", type: "string" },
            { name: "evidence1Stat3Value", type: "string" },
            { name: "evidence1Stat3Description", type: "string" },
            { name: "evidence2Title", type: "string" },
            { name: "evidence2Location", type: "string" },
            { name: "evidence2SourceUrl", type: "url" },
            { name: "evidence2SourceLabel", type: "string" },
            { name: "evidence2Stat1Value", type: "string" },
            { name: "evidence2Stat1Description", type: "string" },
            { name: "evidence2Stat2Value", type: "string" },
            { name: "evidence2Stat2Description", type: "string" },
            { name: "evidence2Stat3Value", type: "string" },
            { name: "evidence2Stat3Description", type: "string" },
            { name: "evidence3Title", type: "string" },
            { name: "evidence3Location", type: "string" },
            { name: "evidence3SourceUrl", type: "url" },
            { name: "evidence3SourceLabel", type: "string" },
            { name: "evidence3Stat1Value", type: "string" },
            { name: "evidence3Stat1Description", type: "string" },
            { name: "evidence3Stat2Value", type: "string" },
            { name: "evidence3Stat2Description", type: "string" },
            { name: "evidence3Stat3Value", type: "string" },
            { name: "evidence3Stat3Description", type: "string" },
            { name: "evidence4Title", type: "string" },
            { name: "evidence4Location", type: "string" },
            { name: "evidence4SourceUrl", type: "url" },
            { name: "evidence4SourceLabel", type: "string" },
            { name: "evidence4Stat1Value", type: "string" },
            { name: "evidence4Stat1Description", type: "string" },
            { name: "evidence4Stat2Value", type: "string" },
            { name: "evidence4Stat2Description", type: "string" },
            { name: "evidence4Stat3Value", type: "string" },
            { name: "evidence4Stat3Description", type: "string" },
            // Quality of Life Cards (6 items)
            { name: "qualityLabel", type: "string" },
            { name: "qualityHeading", type: "string" },
            { name: "qualityBody", type: "text" },
            { name: "qualityCard1Title", type: "string" },
            { name: "qualityCard1Description", type: "text" },
            { name: "qualityCard1SourceUrl", type: "url" },
            { name: "qualityCard1SourceLabel", type: "string" },
            { name: "qualityCard2Title", type: "string" },
            { name: "qualityCard2Description", type: "text" },
            { name: "qualityCard3Title", type: "string" },
            { name: "qualityCard3Description", type: "text" },
            { name: "qualityCard4Title", type: "string" },
            { name: "qualityCard4Description", type: "text" },
            { name: "qualityCard4SourceUrl", type: "url" },
            { name: "qualityCard4SourceLabel", type: "string" },
            { name: "qualityCard5Title", type: "string" },
            { name: "qualityCard5Description", type: "text" },
            { name: "qualityCard6Title", type: "string" },
            { name: "qualityCard6Description", type: "text" },
            { name: "ctaTitle", type: "string" },
            { name: "ctaDescription", type: "text" },
          ],
        },
      ],
      assetsConfig: {
        referenceType: "static",
        staticDir: "public",
        uploadDir: "images",
        publicPath: "/",
      },
    }),
  ],
});
